

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "hypopg" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "index_advisor" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."test_files" (
    "id" bigint NOT NULL,
    "timeStamp" bigint[] NOT NULL,
    "distance" double precision[] NOT NULL,
    "velocity" double precision[] NOT NULL,
    "heading" double precision[] NOT NULL,
    "trajectory_x" double precision[] NOT NULL,
    "trajectory_y" double precision[] NOT NULL,
    "gyro_left" double precision[],
    "gyro_right" double precision[],
    "accel_left" double precision[],
    "displacement" double precision[],
    "gyro_left_smoothed" double precision[],
    "gyro_right_smoothed" double precision[],
    "accel_right" double precision[]
);


ALTER TABLE "public"."test_files" OWNER TO "postgres";


ALTER TABLE "public"."test_files" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Test Files_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test_info" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "test_name" "text" DEFAULT 'test_data'::"text" NOT NULL,
    "comments" "text",
    "recorded_by_user_id" "uuid",
    "metrics" "jsonb",
    "test_file_id" bigint
);


ALTER TABLE "public"."test_info" OWNER TO "postgres";


ALTER TABLE "public"."test_info" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Test Info_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."calibrations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "calibration_name" "text" NOT NULL,
    "wheel_distance" double precision NOT NULL,
    "left_gain" double precision NOT NULL,
    "right_gain" double precision NOT NULL,
    "smarthub_id" "text" NOT NULL,
    "raw_data" "jsonb"
);


ALTER TABLE "public"."calibrations" OWNER TO "postgres";


ALTER TABLE "public"."calibrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."calibrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."test_files"
    ADD CONSTRAINT "Test Files_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test_info"
    ADD CONSTRAINT "Test Info_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."calibrations"
    ADD CONSTRAINT "calibrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test_info"
    ADD CONSTRAINT "test_info_recorded_by_user_id_fkey" FOREIGN KEY ("recorded_by_user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."test_info"
    ADD CONSTRAINT "test_info_test_file_id_fkey" FOREIGN KEY ("test_file_id") REFERENCES "public"."test_files"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Enable Read Access for Users" ON "public"."calibrations" FOR SELECT USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."test_files" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."test_info" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Enable insert for users" ON "public"."calibrations" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Enable read access for all users" ON "public"."test_files" FOR SELECT USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Enable read access for all users" ON "public"."test_info" FOR SELECT USING (("auth"."uid"() IS NOT NULL));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































































































































GRANT ALL ON TABLE "public"."test_files" TO "anon";
GRANT ALL ON TABLE "public"."test_files" TO "authenticated";
GRANT ALL ON TABLE "public"."test_files" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Test Files_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Test Files_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Test Files_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test_info" TO "anon";
GRANT ALL ON TABLE "public"."test_info" TO "authenticated";
GRANT ALL ON TABLE "public"."test_info" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Test Info_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Test Info_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Test Info_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."calibrations" TO "anon";
GRANT ALL ON TABLE "public"."calibrations" TO "authenticated";
GRANT ALL ON TABLE "public"."calibrations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."calibrations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."calibrations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."calibrations_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























